[package]
name = "custom-tracing-layer"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
shuttle-runtime = "0.23.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tokio = "1.28.2"
