[package]
name = "authentication"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
jsonwebtoken = { version = "8.1.1", default-features = false }
lazy_static = "1.4.0"
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0.148", features = ["derive"] }
shuttle-rocket = "0.45.0"
shuttle-runtime = "0.45.0"
tokio = "1.26.0"
