[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = "0.37.5"
shuttle-salvo = { version = "0.12.0-rc1" }
shuttle-runtime = { version = "0.12.0-rc1" }
tokio = { version = "1.26.0" }

