[package]
name = "opendal-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
opendal = "0.51"
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0.148", features = ["derive"] }
shuttle-opendal = "0.53.0"
shuttle-rocket = "0.53.0"
shuttle-runtime = "0.53.0"
tokio = "1.26.0"
