[package]
name = "mongodb-poem-app"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.4.0"
poem = "1.3.55"
shuttle-poem = { version = "0.12.0" }
shuttle-shared-db = { version = "0.12.0", features = ["mongodb"] }
shuttle-runtime = { version = "0.12.0" }
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.26.0" }
