[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = "0.5.2"
shuttle-poise = { version = "0.14.0" }
shuttle-runtime = { version = "0.14.0" }
shuttle-secrets = "0.14.0"
tracing = "0.1.37"
tokio = { version = "1.26.0" }
