[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "0.14.23", features = ["full"] }
shuttle-runtime = { version = "0.1.0" }
shuttle-tower = { version = "0.1.0" }
tower = { version = "0.4.13", features = ["full"] }
tokio = { version = "1.26.0" }
