[package]
name = "shuttle-bevy-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
shuttle-axum = { version = "0.51.0", default-features = false, features = ["axum-0-7"] }
shuttle-runtime = "0.51.0"
tokio = "1.28.2"
tower-http = { version = "0.5.0", features = ["fs"] }
