[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.10", features = ["ws"] }
chrono = { version = "0.4.23", features = ["serde"] }
futures = "0.3.25"
hyper = { version = "0.14.23", features = ["client", "http2"] }
hyper-tls = "0.5.0"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
shuttle-axum = { version = "0.1.0" }
shuttle-runtime = { version = "0.1.0" }
shuttle-static-folder = "0.8.0"
tokio = { version = "1.26.0" }
tower-http = { version = "0.3.0", features = ["fs"] }
