[package]
name = "persist"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0.148", features = ["derive"] }
shuttle-persist = "0.7.2"
shuttle-service = { version = "0.7.2", features = ["web-rocket"] }
