[package]
name = "pdo"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.56"
axum = "0.7.3"
serde = { version = "1", features = ["derive"] }
shuttle-service = "0.54.0"
shuttle-axum = { version = "0.54.0", default-features = false, features = ["axum-0-7"] }
shuttle-runtime = "0.54.0"
tokio = "1.28.2"
