[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
shuttle-serenity = { version = "0.13.0" }
shuttle-runtime = { version = "0.13.0" }
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
shuttle-secrets = "0.13.0"
tokio = { version = "1.26.0" }
tracing = "0.1.37"
