[package]
name = "secrets"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.66"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
shuttle-secrets = "0.10.0"
shuttle-service = { version = "0.10.0", features = ["web-rocket"] }
