[package]
name = "secrets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
rocket = "0.5.0"
shuttle-rocket = "0.35.1"
shuttle-runtime = "0.35.1"
shuttle-secrets = "0.35.1"
tokio = "1.26.0"
