[package]
name = "secrets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
rocket = "0.5.0-rc.4"
shuttle-rocket = "0.34.0"
shuttle-runtime = "0.34.0"
shuttle-secrets = "0.34.0"
tokio = "1.26.0"
