[package]
name = "secrets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
rocket = "0.5.0-rc.2"
shuttle-rocket = { version = "0.1.0" }
shuttle-runtime = { version = "0.1.0" }
shuttle-secrets = "0.11.0"
tokio = { version = "1.26.0" }
