[package]
name = "actix-react-clerk"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
actix-files = "0.6.5"
clerk-rs = "0.2.3"
openssl-sys = { version = "0.9.9", features = ["vendored"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shuttle-actix-web = "0.57.0"
shuttle-runtime = "0.57.0"
