[package]
name = "static-files"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.18"
shuttle-axum = "0.20.0"
shuttle-runtime = "0.20.0"
shuttle-static-folder = "0.20.0"
tokio = "1.28.2"
tower-http = { version = "0.4.0", features = ["fs"] }
