[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
clerk-rs = "0.2.3"
dotenv = "0.15.0"
openssl-sys = { version = "0.9.9", features = ["vendored"] }
serde = { version = "1.0.9", features = ["derive"] }
serde_json = "1.0"
shuttle-actix-web = "0.37.0"
shuttle-runtime = "0.37.0"
