[package]
name = "request-scheduler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.3"
chrono = "0.4.24"
cron = "0.12.0"
reqwest = "0.11.17"
serde = "1.0.163"
shuttle-persist = "0.43.0"
shuttle-runtime = "0.43.0"
tokio = "1.28.0"
tracing = "0.1.37"
